name: sattva_rituals
description: "A high-performance Flutter Web E-commerce application for an Ayurvedic Product Brand."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.0.0
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/Sattva.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/Sattva.png"
    background_color: "#8CC63F"
    theme_color: "#8CC63F"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/icon/
